const foodItem = [
  {
    id: 1,
    name: "Diamond x 22",
    category: "diamonds",
    price: 0.43,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Diamond x 42",
    category: "diamonds",
    price: 0.82,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Diamond x 56",
    category: "diamonds",
    price: 0.92,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 4,
    name: "Diamond x 70",
    category: "diamonds",
    price: 1.3,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 5,
    name: "Diamond x 86",
    category: "diamonds",
    price: 1.22,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 6,
    name: "Diamond x 112",
    category: "diamonds",
    price: 1.75,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 7,
    name: "Diamond x 140",
    category: "diamonds",
    price: 2.5,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 8,
    name: "Diamond x 172",
    category: "diamonds",
    price: 2.32,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 9,
    name: "Diamond x 233",
    category: "diamonds",
    price: 3.4,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 10,
    name: "Diamond x 257",
    category: "diamonds",
    price: 3.31,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 11,
    name: "Diamond x 284",
    category: "diamonds",
    price: 4.9,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 12,
    name: "Diamond x 336",
    category: "diamonds",
    price: 5.05,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 13,
    name: "Diamond x 355",
    category: "diamonds",
    price: 6.1,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 14,
    name: "Diamond x 429",
    category: "diamonds",
    price: 7.2,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 15,
    name: "Diamond x 570",
    category: "diamonds",
    price: 8.33,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 16,
    name: "Diamond x 706",
    category: "diamonds",
    price: 8.83,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 17,
    name: "Diamond x 716",
    category: "diamonds",
    price: 12.1,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 18,
    name: "Diamond x 1084",
    category: "diamonds",
    price: 18.1,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 19,
    name: "Diamond x 1163",
    category: "diamonds",
    price: 16.01,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 20,
    name: "Diamond x 1446",
    category: "diamonds",
    price: 24.02,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 21,
    name: "Diamond x 2195",
    category: "diamonds",
    price: 26.52,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 22,
    name: "Diamond x 2398",
    category: "diamonds",
    price: 33.1,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 23,
    name: "Diamond x 2976",
    category: "diamonds",
    price: 48.1,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 24,
    name: "Diamond x 3688",
    category: "diamonds",
    price: 44.22,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 25,
    name: "Diamond x 5042",
    category: "diamonds",
    price: 82.5,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 26,
    name: "Diamond x 5532",
    category: "diamonds",
    price: 66.8,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 27,
    name: "Diamond x 7502",
    category: "diamonds",
    price: 119.7,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 28,
    name: "Diamond x 9288",
    category: "diamonds",
    price: 110.7,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 29,
    name: "Diamond x 46440",
    category: "promo",
    price: 555.0,
    img: "images/diamonds/d1.png",
    quantity: 1,
  },
  {
    id: 30,
    name: "Weekly Pass",
    category: "weekly",
    price: 1.49,
    img: "images/weekly/wp.png",
    quantity: 1,
  },
  {
    id: 31,
    name: "Twilight Pass",
    category: "twilight",
    price: 7.42,
    img: "images/twilight/tp.png",
    quantity: 1,
  },
  {
    id: 31,
    name: "Starlight",
    category: "starlight",
    price: 4.22,
    img: "images/starlight/s.png",
    quantity: 1,
  },
  {
    id: 31,
    name: "Starlight Premium",
    category: "starlight",
    price: 9.8,
    img: "images/starlight/sp.png",
    quantity: 1,
  },
];
export { foodItem };
